#==============================================================
#
#  Name: Makefile 
#
#  Facility: LCLS Magnets
#
#  Auth: 28-Nov-2007, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, First Lastname  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#       dd-mmm-yyyy, First Lastname   (USERNAME):
#         comment
#
#==============================================================
#
TOP = ..
include $(TOP)/configure/CONFIG
DIRS += $(wildcard *ioc*)
include $(EPICS_BASE)/configure/RULES_DIRS

