#==============================================================
#
#  Name: Makefile for ioc startup scripts
#
#  Facility: LCLS Magnets
#
#  Auth: 28-Nov-2007, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, First Lastname  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#       dd-mmm-yyyy, First Lastname   (USERNAME):
#         comment
#
#==============================================================
#
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#========================================
#
ARCH    = RTEMS-beatnik
TARGETS = envPaths

include $(TOP)/configure/RULES.ioc
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#======================================== 
#
# End of file