#==============================================================
#
#  Name: Makefile
#
#  Auth: 10-Dec-2007, K. Luchini     (LUCHINI)
#  Rev:  dd-mmm-yyyy, First Lastname (USERNAME)
#
#--------------------------------------------------------------
#  Mod:
#       dd-mmm-yyyy, First Lastname (USERNAME):
#         comments
#
#=============================================================
#
TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#========================================
#
DOCS += mcor_noise.jpeg
DOCS += avgr_reg_descrip_v3.pdf

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

